# NWEA Categories

The purpose of this notebook is to take the RIT scores that students earn on the different categories (goals) on NWEA and convert them to a percentage. The chart from the NWEA technical manual will be used but this only shows RIT scores by every five percentile so the performance will only be able to be reflected to the near fifth percentile.

In [ ]:
import numpy as np
import pandas as pd

## Loading Data

The roster has to be obtained from the Aeries query that is given. NWEA results need to be the raw data file from the NWEA site. The percentile charts were taken from the technical manual for NWEA. They can be obtained through a pdf upload in excel but have to have a separate file generated for each subject and the time of year the test was taken. The percentiles of 1 and 99 percent have to be created rows based on the lowest possible score (100) and the highest possible score (350).

In [2]:
# LIST STU SC ID NM GR LF SPECIALED 
roster = pd.read_excel(r"C:\Users\derek.castleman\OneDrive - Wonderful College Prep Academy\Desktop\Roster NWEA.xlsx")

fall_math = pd.read_excel(r"C:\Users\derek.castleman\OneDrive - Wonderful College Prep Academy\Desktop\NWEA Categories\Fall Math.xlsx")
fall_ela = pd.read_excel(r"C:\Users\derek.castleman\OneDrive - Wonderful College Prep Academy\Desktop\NWEA Categories\Fall ELA.xlsx")
winter_math = pd.read_excel(r"C:\Users\derek.castleman\OneDrive - Wonderful College Prep Academy\Desktop\NWEA Categories\Winter Math.xlsx")
winter_ela = pd.read_excel(r"C:\Users\derek.castleman\OneDrive - Wonderful College Prep Academy\Desktop\NWEA Categories\Winter ELA.xlsx")

nwea = pd.read_csv(r"C:\Users\derek.castleman\OneDrive - Wonderful College Prep Academy\Desktop\AssessmentResults.csv")

C:\Users\derek.castleman\AppData\Local\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [3]:
roster

,School,Student ID,Student Name,Grade,LangFlu,SPECIALED Value
0,1,1095014,"A Cerda, Eddie",12,R,No
1,1,1094167,"Aaron, Anastasia",7,E,No
2,4,1095258,"Aaron, Lillie",4,E,No
3,4,1096128,"Aburto-Ramirez, Anaiah",2,L,No
4,4,1093925,"Aburto-Ramirez, Ayden",5,L,No
...,...,...,...,...,...,...
2362,6,1095271,"Zuniga, Alan",4,L,No
2363,8,1092848,"Zuniga, Michelle",8,R,No
2364,4,1094487,"Zuniga, Pedro",6,R,No
2365,6,1096578,"Zuniga, Zoe",1,E,No
2366,6,1094375,"Zuniga Vazquez, Luis",6,R,No

### Fixing Charts

First an input will be asked in which you will have to choose the time of year for the tests, allowing for the right charts to be selected. The charts will then be melted to turn all the grades and their associated scores into columns for each associated percentile.

In [4]:
a = input("What test are you interested in: Fall or Winter?") #Input the time of year of interest
a

What test are you interested in: Fall or Winter? Fall

'Fall'

In [5]:
# Takes the input and runs through an if then statement to find the correct charts
if a == "Fall":
    nwea_math = fall_math
    nwea_ela = fall_ela
else:
    nwea_math = winter_math
    nwea_ela = winter_ela

In [6]:
nwea_math

    Pct    K    1    2    3    4    5    6    7    8    9   10   11   12
0     1  100  100  100  100  100  100  100  100  100  100  100  100  100
1     5  121  137  147  158  171  180  184  189  192  196  196  195  194
2    10  125  142  153  164  177  185  190  195  199  202  203  203  201
3    15  128  145  157  168  181  189  194  199  203  207  208  208  206
4    20  131  148  160  171  184  193  197  203  207  210  211  212  211
5    25  133  150  162  174  186  195  199  206  210  213  214  215  214
6    30  135  152  165  176  189  198  202  208  212  216  217  218  217
7    35  136  154  167  178  191  200  204  211  215  218  220  221  220
8    40  138  156  169  180  193  202  206  213  217  220  222  224  223
9    45  140  158  171  182  195  204  208  215  220  223  224  227  226
10   50  141  159  173  184  197  206  210  217  222  225  227  229  228
11   55  143  161  175  186  199  208  212  219  224  227  229  232  231
12   60  144  163  177  188  201  210  214  222  227  229  232  234  233
13   65  146  164  179  190  203  212  216  224  229  232  234  237  236
14   70  148  166  181  192  205  215  219  226  232  234  237  240  239
15   75  149  168  183  195  208  217  221  229  234  237  239  243  242
16   80  152  171  186  197  210  220  224  232  237  240  242  246  246
17   85  154  173  189  200  214  223  227  235  241  243  246  250  250
18   90  157  176  193  204  217  227  231  239  246  248  251  255  255
19   95  161  181  198  210  223  233  237  246  252  254  257  263  263
20   99  350  350  350  350  350  350  350  350  350  350  350  350  350

In [7]:
nwea_ela

    Pct    K    1    2    3    4    5    6    7    8    9   10   11   12
0     1  100  100  100  100  100  100  100  100  100  100  100  100  100
1     5  131  145  158  171  182  190  296  199  202  201  202  200  198
2    10  132  148  161  174  185  193  299  202  205  205  205  203  202
3    15  134  149  162  176  187  195  201  204  207  207  207  206  204
4    20  134  150  164  177  188  196  202  205  208  208  209  208  206
5    25  135  151  165  179  190  197  203  207  210  210  211  210  208
6    30  136  152  166  180  191  199  205  208  211  211  212  211  209
7    35  137  153  167  181  192  200  206  209  212  212  213  212  211
8    40  137  154  168  182  193  201  207  210  213  214  215  214  212
9    45  138  155  169  183  194  202  207  211  214  215  216  215  214
10   50  138  155  170  184  195  203  208  212  215  216  217  216  215
11   55  139  156  171  185  196  204  209  213  216  217  218  218  216
12   60  139  157  172  186  197  205  210  214  217  218  219  219  217
13   65  140  158  173  187  198  206  211  215  218  219  220  220  219
14   70  141  158  174  189  200  207  212  216  219  220  222  222  220
15   75  141  159  175  190  201  208  213  217  220  222  223  223  222
16   80  142  160  176  191  202  210  215  218  222  223  225  225  223
17   85  143  161  178  193  204  211  216  220  223  225  226  227  225
18   90  144  163  180  195  206  213  218  221  225  227  229  229  228
19   95  146  165  182  198  209  216  221  224  228  230  232  233  232
20   99  350  350  350  350  350  350  350  350  350  350  350  350  350

In [8]:
# Melts the math chart for grades with a value for score
math_melt = nwea_math.melt(id_vars=["Pct"], var_name="Grade", value_name="Score")
math_melt

     Pct Grade  Score
0      1     K    100
1      5     K    121
2     10     K    125
3     15     K    128
4     20     K    131
..   ...   ...    ...
268   80    12    246
269   85    12    250
270   90    12    255
271   95    12    263
272   99    12    350

[273 rows x 3 columns]

In [9]:
# Melts the ELA chart similar to Math
ela_melt = nwea_ela.melt(id_vars=["Pct"], var_name="Grade", value_name="Score")
ela_melt

     Pct Grade  Score
0      1     K    100
1      5     K    131
2     10     K    132
3     15     K    134
4     20     K    134
..   ...   ...    ...
268   80    12    223
269   85    12    225
270   90    12    228
271   95    12    232
272   99    12    350

[273 rows x 3 columns]

## NWEA Cleaning

All that happens in this section is that the rows that are False for a growth measure are eliminated to leave only the results that earned a Growth measure in MAP. This will eliminate students who took duplicate tests in the process. Then two dataframes are created with one being for Math and the other being for ELA. Then the columns that are associated with the first four claims are selected since these are the only ones that have data.

In [10]:
nwea

,TermName,DistrictName,District_StateID,SchoolName,School_StateID,StudentID,Student_StateID,Subject,Course,GrowthMeasureYN,...,ProjectedProficiencyStudy6,ProjectedProficiencyLevel6,ProjectedProficiencyStudy7,ProjectedProficiencyLevel7,ProjectedProficiencyStudy8,ProjectedProficiencyLevel8,ProjectedProficiencyStudy9,ProjectedProficiencyLevel9,ProjectedProficiencyStudy10,ProjectedProficiencyLevel10
0,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Academy,NaN,1092314,8188745635,Mathematics,Math K-12,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Academy,NaN,1092314,8188745635,Language Arts,Reading,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Academy,NaN,1092314,8188745635,Science,Science K-12,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Academy,NaN,1092319,8758597691,Mathematics,Math K-12,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Academy,NaN,1092319,8758597691,Language Arts,Reading,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5449,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Elementary Lost Hills,NaN,1097076,5345600657,Language Arts,Reading,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5450,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Elementary,NaN,1097093,1408464077,Mathematics,Math K-12,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5451,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Elementary,NaN,1097093,1408464077,Language Arts,Reading,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5452,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Elementary,NaN,1097094,7698326692,Mathematics,Math K-12,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5453,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Elementary,NaN,1097118,1054705364,Mathematics,Math K-12,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# Selects rows that are not false for Growth Measure
nwea = nwea[nwea['GrowthMeasureYN'] != False]
nwea

,TermName,DistrictName,District_StateID,SchoolName,School_StateID,StudentID,Student_StateID,Subject,Course,GrowthMeasureYN,...,ProjectedProficiencyStudy6,ProjectedProficiencyLevel6,ProjectedProficiencyStudy7,ProjectedProficiencyLevel7,ProjectedProficiencyStudy8,ProjectedProficiencyLevel8,ProjectedProficiencyStudy9,ProjectedProficiencyLevel9,ProjectedProficiencyStudy10,ProjectedProficiencyLevel10
0,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Academy,NaN,1092314,8188745635,Mathematics,Math K-12,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Academy,NaN,1092314,8188745635,Language Arts,Reading,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Academy,NaN,1092314,8188745635,Science,Science K-12,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Academy,NaN,1092319,8758597691,Mathematics,Math K-12,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Academy,NaN,1092319,8758597691,Language Arts,Reading,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5449,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Elementary Lost Hills,NaN,1097076,5345600657,Language Arts,Reading,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5450,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Elementary,NaN,1097093,1408464077,Mathematics,Math K-12,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5451,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Elementary,NaN,1097093,1408464077,Language Arts,Reading,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5452,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Elementary,NaN,1097094,7698326692,Mathematics,Math K-12,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5453,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Elementary,NaN,1097118,1054705364,Mathematics,Math K-12,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
# Selects Math
math = nwea[nwea['Subject'] == 'Mathematics']
math

,TermName,DistrictName,District_StateID,SchoolName,School_StateID,StudentID,Student_StateID,Subject,Course,GrowthMeasureYN,...,ProjectedProficiencyStudy6,ProjectedProficiencyLevel6,ProjectedProficiencyStudy7,ProjectedProficiencyLevel7,ProjectedProficiencyStudy8,ProjectedProficiencyLevel8,ProjectedProficiencyStudy9,ProjectedProficiencyLevel9,ProjectedProficiencyStudy10,ProjectedProficiencyLevel10
0,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Academy,NaN,1092314,8188745635,Mathematics,Math K-12,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Academy,NaN,1092319,8758597691,Mathematics,Math K-12,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Academy,NaN,1092320,6198147843,Mathematics,Math K-12,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Academy,NaN,1092327,9472427302,Mathematics,Math K-12,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Academy,NaN,1092329,5594174583,Mathematics,Math K-12,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5446,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Elementary,NaN,1097074,3761640832,Mathematics,Math K-12,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5448,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Elementary Lost Hills,NaN,1097076,5345600657,Mathematics,Math K-12,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5450,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Elementary,NaN,1097093,1408464077,Mathematics,Math K-12,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5452,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Elementary,NaN,1097094,7698326692,Mathematics,Math K-12,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5453,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Elementary,NaN,1097118,1054705364,Mathematics,Math K-12,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
# Selects ELA
ela = nwea[nwea['Subject'] == 'Language Arts']
ela

,TermName,DistrictName,District_StateID,SchoolName,School_StateID,StudentID,Student_StateID,Subject,Course,GrowthMeasureYN,...,ProjectedProficiencyStudy6,ProjectedProficiencyLevel6,ProjectedProficiencyStudy7,ProjectedProficiencyLevel7,ProjectedProficiencyStudy8,ProjectedProficiencyLevel8,ProjectedProficiencyStudy9,ProjectedProficiencyLevel9,ProjectedProficiencyStudy10,ProjectedProficiencyLevel10
1,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Academy,NaN,1092314,8188745635,Language Arts,Reading,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Academy,NaN,1092319,8758597691,Language Arts,Reading,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Academy,NaN,1092320,6198147843,Language Arts,Reading,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Academy,NaN,1092327,9472427302,Language Arts,Reading,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Academy,NaN,1092329,5594174583,Language Arts,Reading,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5443,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Academy,NaN,1097070,3155882747,Language Arts,Reading,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5445,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Elementary Lost Hills,NaN,1097073,8064196694,Language Arts,Reading,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5447,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Elementary,NaN,1097074,3761640832,Language Arts,Reading,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5449,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Elementary Lost Hills,NaN,1097076,5345600657,Language Arts,Reading,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5451,Fall 2025-2026,Wonderful Agriculture Career Prep,NaN,Wonderful College Prep Elementary,NaN,1097093,1408464077,Language Arts,Reading,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
# Selects the columns of interest in Math
math_columns = math.iloc[:, [5, 7, 77, 78, 81, 82, 83, 86, 87, 88, 91, 92, 93, 96]]
math_columns

,StudentID,Subject,Goal1Name,Goal1RitScore,Goal1Adjective,Goal2Name,Goal2RitScore,Goal2Adjective,Goal3Name,Goal3RitScore,Goal3Adjective,Goal4Name,Goal4RitScore,Goal4Adjective
0,1092314,Mathematics,Operations and Algebraic Thinking,189.0,Low,The Real and Complex Number Systems,189.0,Low,Geometry,201.0,Low,Statistics and Probability,196.0,Low
3,1092319,Mathematics,Operations and Algebraic Thinking,241.0,High,The Real and Complex Number Systems,238.0,High,Geometry,230.0,HiAvg,Statistics and Probability,212.0,LoAvg
6,1092320,Mathematics,Operations and Algebraic Thinking,241.0,High,The Real and Complex Number Systems,255.0,High,Geometry,243.0,High,Statistics and Probability,250.0,High
9,1092327,Mathematics,Operations and Algebraic Thinking,239.0,High,The Real and Complex Number Systems,251.0,High,Geometry,239.0,High,Statistics and Probability,239.0,High
12,1092329,Mathematics,Operations and Algebraic Thinking,244.0,High,The Real and Complex Number Systems,251.0,High,Geometry,241.0,High,Statistics and Probability,240.0,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5446,1097074,Mathematics,Operations and Algebraic Thinking,163.0,HiAvg,Number and Operations,149.0,LoAvg,Measurement and Data,151.0,LoAvg,Geometry,146.0,Low
5448,1097076,Mathematics,Operations and Algebraic Thinking,168.0,Low,Number and Operations,169.0,Low,Measurement and Data,177.0,LoAvg,Geometry,163.0,Low
5450,1097093,Mathematics,Operations and Algebraic Thinking,192.0,HiAvg,Number and Operations,177.0,LoAvg,Measurement and Data,182.0,Avg,Geometry,172.0,LoAvg
5452,1097094,Mathematics,Operations and Algebraic Thinking,206.0,High,Number and Operations,202.0,High,Measurement and Data,207.0,High,Geometry,204.0,High
5453,1097118,Mathematics,Operations and Algebraic Thinking,191.0,Low,The Real and Complex Number Systems,207.0,Avg,Geometry,212.0,Avg,Statistics and Probability,212.0,Avg

In [15]:
# Selects the columns of interest in ELA
ela_columns = ela.iloc[:, [5, 7, 77, 78, 81, 82, 83, 86, 87, 88, 91, 92, 93, 96]]
ela_columns

,StudentID,Subject,Goal1Name,Goal1RitScore,Goal1Adjective,Goal2Name,Goal2RitScore,Goal2Adjective,Goal3Name,Goal3RitScore,Goal3Adjective,Goal4Name,Goal4RitScore,Goal4Adjective
1,1092314,Language Arts,Literary Text,212.0,Avg,Informational Text,200.0,Low,Vocabulary,192.0,Low,NaN,NaN,NaN
4,1092319,Language Arts,Literary Text,226.0,HiAvg,Informational Text,229.0,HiAvg,Vocabulary,230.0,HiAvg,NaN,NaN,NaN
7,1092320,Language Arts,Literary Text,228.0,HiAvg,Informational Text,238.0,High,Vocabulary,233.0,High,NaN,NaN,NaN
10,1092327,Language Arts,Literary Text,221.0,HiAvg,Informational Text,224.0,HiAvg,Vocabulary,229.0,HiAvg,NaN,NaN,NaN
13,1092329,Language Arts,Literary Text,242.0,High,Informational Text,241.0,High,Vocabulary,247.0,High,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5443,1097070,Language Arts,Literary Text,227.0,HiAvg,Informational Text,191.0,Low,Vocabulary,224.0,HiAvg,NaN,NaN,NaN
5445,1097073,Language Arts,Literary Text,160.0,Low,Informational Text,158.0,Low,Vocabulary,156.0,Low,NaN,NaN,NaN
5447,1097074,Language Arts,Foundational Skills,150.0,LoAvg,Language and Writing,158.0,Avg,Literature and Informational Text,147.0,LoAvg,Vocabulary Use and Functions,149.0,LoAvg
5449,1097076,Language Arts,Literary Text,164.0,Low,Informational Text,171.0,LoAvg,Vocabulary,168.0,Low,NaN,NaN,NaN
5451,1097093,Language Arts,Literary Text,195.0,HiAvg,Informational Text,188.0,Avg,Vocabulary,183.0,Avg,NaN,NaN,NaN

### Roster Cleanup

The issue with the roster is that students in kindergarten are listed as 0 so this value is changed with K.

In [16]:
roster.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2367 entries, 0 to 2366
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   School           2367 non-null   int64
 1   Student ID       2367 non-null   int64
 2   Student Name     2367 non-null   object
 3   Grade            2367 non-null   int64
 4   LangFlu          2367 non-null   object
 5   SPECIALED Value  2367 non-null   object
dtypes: int64(3), object(3)
memory usage: 111.1+ KB

In [17]:
roster['Grade'] = roster['Grade'].replace(0, 'K')
roster.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2367 entries, 0 to 2366
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   School           2367 non-null   int64
 1   Student ID       2367 non-null   int64
 2   Student Name     2367 non-null   object
 3   Grade            2367 non-null   object
 4   LangFlu          2367 non-null   object
 5   SPECIALED Value  2367 non-null   object
dtypes: int64(2), object(4)
memory usage: 111.1+ KB

In [18]:
roster

      School  Student ID            Student Name Grade LangFlu SPECIALED Value
0          1     1095014          A Cerda, Eddie    12       R              No
1          1     1094167        Aaron, Anastasia     7       E              No
2          4     1095258           Aaron, Lillie     4       E              No
3          4     1096128  Aburto-Ramirez, Anaiah     2       L              No
4          4     1093925   Aburto-Ramirez, Ayden     5       L              No
...      ...         ...                     ...   ...     ...             ...
2362       6     1095271            Zuniga, Alan     4       L              No
2363       8     1092848        Zuniga, Michelle     8       R              No
2364       4     1094487           Zuniga, Pedro     6       R              No
2365       6     1096578             Zuniga, Zoe     1       E              No
2366       6     1094375    Zuniga Vazquez, Luis     6       R              No

[2367 rows x 6 columns]

### Math

The first thing will be that the Math is merged with the student roster. Then each claim (one through four) will be selected by choosing the columns that are associated with, grabbing the claim name, level and RIT score that is associated with it. Then each claim will be merged with the Math chart. For the merge the function merge_asof will be used allowing the RIT score to match with the closest percentage but if there is a tie between percentages then the lowest one will be selected due to the restriction of the function.  When all the claims have been matched they will then all be merged to create one data frame with them all.

In [19]:
# Merges Math MAP results with the roster
math = pd.merge(roster, math_columns, how='inner', left_on='Student ID', right_on='StudentID')
math

,School,Student ID,Student Name,Grade,LangFlu,SPECIALED Value,StudentID,Subject,Goal1Name,Goal1RitScore,Goal1Adjective,Goal2Name,Goal2RitScore,Goal2Adjective,Goal3Name,Goal3RitScore,Goal3Adjective,Goal4Name,Goal4RitScore,Goal4Adjective
0,1,1094167,"Aaron, Anastasia",7,E,No,1094167,Mathematics,Operations and Algebraic Thinking,203.0,Low,The Real and Complex Number Systems,209.0,LoAvg,Geometry,228.0,HiAvg,Statistics and Probability,246.0,High
1,4,1095258,"Aaron, Lillie",4,E,No,1095258,Mathematics,Operations and Algebraic Thinking,199.0,Avg,Number and Operations,204.0,HiAvg,Measurement and Data,206.0,HiAvg,Geometry,199.0,Avg
2,4,1096128,"Aburto-Ramirez, Anaiah",2,L,No,1096128,Mathematics,Operations and Algebraic Thinking,173.0,Avg,Number and Operations,169.0,LoAvg,Measurement and Data,162.0,LoAvg,Geometry,184.0,HiAvg
3,4,1093925,"Aburto-Ramirez, Ayden",5,L,No,1093925,Mathematics,Operations and Algebraic Thinking,212.0,HiAvg,Number and Operations,208.0,Avg,Measurement and Data,191.0,Low,Geometry,202.0,LoAvg
4,4,1096854,"Abuyen, Jhene",K,E,No,1096854,Mathematics,Operations and Algebraic Thinking,130.0,Low,Number and Operations,140.0,Avg,Measurement and Data,147.0,HiAvg,Geometry,154.0,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2051,4,1096922,"Zepeda Salas, Francisco",K,E,No,1096922,Mathematics,Operations and Algebraic Thinking,133.0,LoAvg,Number and Operations,139.0,Avg,Measurement and Data,141.0,Avg,Geometry,138.0,LoAvg
2052,6,1095271,"Zuniga, Alan",4,L,No,1095271,Mathematics,Operations and Algebraic Thinking,205.0,HiAvg,Number and Operations,196.0,Avg,Measurement and Data,179.0,Low,Geometry,199.0,Avg
2053,8,1092848,"Zuniga, Michelle",8,R,No,1092848,Mathematics,Operations and Algebraic Thinking,222.0,Avg,The Real and Complex Number Systems,218.0,Avg,Geometry,205.0,Low,Statistics and Probability,218.0,Avg
2054,6,1096578,"Zuniga, Zoe",1,E,No,1096578,Mathematics,Operations and Algebraic Thinking,172.0,High,Number and Operations,169.0,HiAvg,Measurement and Data,159.0,Avg,Geometry,163.0,HiAvg
2055,6,1094375,"Zuniga Vazquez, Luis",6,R,No,1094375,Mathematics,Operations and Algebraic Thinking,226.0,High,The Real and Complex Number Systems,191.0,Low,Geometry,204.0,LoAvg,Statistics and Probability,194.0,Low

In [20]:
# Selects the data for claim one
claim_one = math.iloc[:, [0, 1, 2, 3, 4, 5, 7, 8, 9, 10]]
claim_one

,School,Student ID,Student Name,Grade,LangFlu,SPECIALED Value,Subject,Goal1Name,Goal1RitScore,Goal1Adjective
0,1,1094167,"Aaron, Anastasia",7,E,No,Mathematics,Operations and Algebraic Thinking,203.0,Low
1,4,1095258,"Aaron, Lillie",4,E,No,Mathematics,Operations and Algebraic Thinking,199.0,Avg
2,4,1096128,"Aburto-Ramirez, Anaiah",2,L,No,Mathematics,Operations and Algebraic Thinking,173.0,Avg
3,4,1093925,"Aburto-Ramirez, Ayden",5,L,No,Mathematics,Operations and Algebraic Thinking,212.0,HiAvg
4,4,1096854,"Abuyen, Jhene",K,E,No,Mathematics,Operations and Algebraic Thinking,130.0,Low
...,...,...,...,...,...,...,...,...,...,...
2051,4,1096922,"Zepeda Salas, Francisco",K,E,No,Mathematics,Operations and Algebraic Thinking,133.0,LoAvg
2052,6,1095271,"Zuniga, Alan",4,L,No,Mathematics,Operations and Algebraic Thinking,205.0,HiAvg
2053,8,1092848,"Zuniga, Michelle",8,R,No,Mathematics,Operations and Algebraic Thinking,222.0,Avg
2054,6,1096578,"Zuniga, Zoe",1,E,No,Mathematics,Operations and Algebraic Thinking,172.0,High
2055,6,1094375,"Zuniga Vazquez, Luis",6,R,No,Mathematics,Operations and Algebraic Thinking,226.0,High

In [21]:
# Selects the columns for claim two
claim_two = math.iloc[:, [0, 1, 2, 3, 4, 5, 7, 11, 12, 13]]
claim_two

,School,Student ID,Student Name,Grade,LangFlu,SPECIALED Value,Subject,Goal2Name,Goal2RitScore,Goal2Adjective
0,1,1094167,"Aaron, Anastasia",7,E,No,Mathematics,The Real and Complex Number Systems,209.0,LoAvg
1,4,1095258,"Aaron, Lillie",4,E,No,Mathematics,Number and Operations,204.0,HiAvg
2,4,1096128,"Aburto-Ramirez, Anaiah",2,L,No,Mathematics,Number and Operations,169.0,LoAvg
3,4,1093925,"Aburto-Ramirez, Ayden",5,L,No,Mathematics,Number and Operations,208.0,Avg
4,4,1096854,"Abuyen, Jhene",K,E,No,Mathematics,Number and Operations,140.0,Avg
...,...,...,...,...,...,...,...,...,...,...
2051,4,1096922,"Zepeda Salas, Francisco",K,E,No,Mathematics,Number and Operations,139.0,Avg
2052,6,1095271,"Zuniga, Alan",4,L,No,Mathematics,Number and Operations,196.0,Avg
2053,8,1092848,"Zuniga, Michelle",8,R,No,Mathematics,The Real and Complex Number Systems,218.0,Avg
2054,6,1096578,"Zuniga, Zoe",1,E,No,Mathematics,Number and Operations,169.0,HiAvg
2055,6,1094375,"Zuniga Vazquez, Luis",6,R,No,Mathematics,The Real and Complex Number Systems,191.0,Low

In [22]:
# Selects the columns for claim three
claim_three = math.iloc[:, [0, 1, 2, 3, 4, 5, 7, 14, 15, 16]]
claim_three

,School,Student ID,Student Name,Grade,LangFlu,SPECIALED Value,Subject,Goal3Name,Goal3RitScore,Goal3Adjective
0,1,1094167,"Aaron, Anastasia",7,E,No,Mathematics,Geometry,228.0,HiAvg
1,4,1095258,"Aaron, Lillie",4,E,No,Mathematics,Measurement and Data,206.0,HiAvg
2,4,1096128,"Aburto-Ramirez, Anaiah",2,L,No,Mathematics,Measurement and Data,162.0,LoAvg
3,4,1093925,"Aburto-Ramirez, Ayden",5,L,No,Mathematics,Measurement and Data,191.0,Low
4,4,1096854,"Abuyen, Jhene",K,E,No,Mathematics,Measurement and Data,147.0,HiAvg
...,...,...,...,...,...,...,...,...,...,...
2051,4,1096922,"Zepeda Salas, Francisco",K,E,No,Mathematics,Measurement and Data,141.0,Avg
2052,6,1095271,"Zuniga, Alan",4,L,No,Mathematics,Measurement and Data,179.0,Low
2053,8,1092848,"Zuniga, Michelle",8,R,No,Mathematics,Geometry,205.0,Low
2054,6,1096578,"Zuniga, Zoe",1,E,No,Mathematics,Measurement and Data,159.0,Avg
2055,6,1094375,"Zuniga Vazquez, Luis",6,R,No,Mathematics,Geometry,204.0,LoAvg

In [23]:
# Selects the columns for claim four
claim_four = math.iloc[:, [0, 1, 2, 3, 4, 5, 7, 17, 18, 19]]
claim_four

,School,Student ID,Student Name,Grade,LangFlu,SPECIALED Value,Subject,Goal4Name,Goal4RitScore,Goal4Adjective
0,1,1094167,"Aaron, Anastasia",7,E,No,Mathematics,Statistics and Probability,246.0,High
1,4,1095258,"Aaron, Lillie",4,E,No,Mathematics,Geometry,199.0,Avg
2,4,1096128,"Aburto-Ramirez, Anaiah",2,L,No,Mathematics,Geometry,184.0,HiAvg
3,4,1093925,"Aburto-Ramirez, Ayden",5,L,No,Mathematics,Geometry,202.0,LoAvg
4,4,1096854,"Abuyen, Jhene",K,E,No,Mathematics,Geometry,154.0,High
...,...,...,...,...,...,...,...,...,...,...
2051,4,1096922,"Zepeda Salas, Francisco",K,E,No,Mathematics,Geometry,138.0,LoAvg
2052,6,1095271,"Zuniga, Alan",4,L,No,Mathematics,Geometry,199.0,Avg
2053,8,1092848,"Zuniga, Michelle",8,R,No,Mathematics,Statistics and Probability,218.0,Avg
2054,6,1096578,"Zuniga, Zoe",1,E,No,Mathematics,Geometry,163.0,HiAvg
2055,6,1094375,"Zuniga Vazquez, Luis",6,R,No,Mathematics,Statistics and Probability,194.0,Low

In [24]:
# Changes the data type for score
math_melt['Score'] = math_melt['Score'].astype('Int64')
math_melt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 273 entries, 0 to 272
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Pct     273 non-null    int64
 1   Grade   273 non-null    object
 2   Score   273 non-null    Int64
dtypes: Int64(1), int64(1), object(1)
memory usage: 6.8+ KB

In [25]:
claim_one.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2056 entries, 0 to 2055
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   School           2056 non-null   int64
 1   Student ID       2056 non-null   int64
 2   Student Name     2056 non-null   object
 3   Grade            2056 non-null   object
 4   LangFlu          2056 non-null   object
 5   SPECIALED Value  2056 non-null   object
 6   Subject          2056 non-null   object
 7   Goal1Name        2056 non-null   object
 8   Goal1RitScore    2054 non-null   float64
 9   Goal1Adjective   2054 non-null   object
dtypes: float64(1), int64(2), object(7)
memory usage: 160.8+ KB

In [26]:
claim_one['Goal1RitScore'] = claim_one['Goal1RitScore'].astype('Int64') #Sets RIT score to same datatype
claim_one = claim_one.dropna(subset=['Goal1RitScore']) # Drops any rows with no RIT score
claim_one = claim_one.sort_values(['Goal1RitScore', 'Grade']) # Sorts values for asof function
math_melt = math_melt.sort_values(['Score', 'Grade']) # Sorts math chart for the function.
# Merges both dataframes on score and selects the nearest Math chart score to Claim RIT score
claim_one = pd.merge_asof(claim_one, math_melt, by='Grade', left_on='Goal1RitScore', right_on = 'Score', direction='nearest')
claim_one

C:\Users\derek.castleman\AppData\Local\Temp\ipykernel_31044\1848309832.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  claim_one['Goal1RitScore'] = claim_one['Goal1RitScore'].astype('Int64')

,School,Student ID,Student Name,Grade,LangFlu,SPECIALED Value,Subject,Goal1Name,Goal1RitScore,Goal1Adjective,Pct,Score
0,4,1096895,"Moreno Ruelas, Eliana",K,E,No,Mathematics,Operations and Algebraic Thinking,103,Low,1,100
1,4,1096961,"Duran, Isaiah",K,E,Yes,Mathematics,Operations and Algebraic Thinking,108,Low,1,100
2,4,1096867,"Cruz, Juan-David",K,E,Yes,Mathematics,Operations and Algebraic Thinking,110,Low,1,100
3,4,1096960,"Hernandez, Mia",K,E,No,Mathematics,Operations and Algebraic Thinking,110,Low,1,100
4,4,1096899,"Pacheco, Aytana",K,E,No,Mathematics,Operations and Algebraic Thinking,110,Low,1,100
...,...,...,...,...,...,...,...,...,...,...,...,...
2049,8,1092547,"Rodriguez Almanza, Alexander",10,R,No,Mathematics,Operations and Algebraic Thinking,272,High,95,257
2050,1,1097001,"Moffett, Levi",9,E,No,Mathematics,Operations and Algebraic Thinking,274,High,95,254
2051,1,1094305,"Rodriguez, Fatima",10,R,No,Mathematics,Operations and Algebraic Thinking,276,High,95,257
2052,1,1093057,"Mercado, Natalie",11,E,No,Mathematics,Operations and Algebraic Thinking,278,High,95,263
2053,1,1094876,"Arreola, Saul",11,I,No,Mathematics,Operations and Algebraic Thinking,285,High,95,263

In [27]:
claim_one.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2054 entries, 0 to 2053
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   School           2054 non-null   int64
 1   Student ID       2054 non-null   int64
 2   Student Name     2054 non-null   object
 3   Grade            2054 non-null   object
 4   LangFlu          2054 non-null   object
 5   SPECIALED Value  2054 non-null   object
 6   Subject          2054 non-null   object
 7   Goal1Name        2054 non-null   object
 8   Goal1RitScore    2054 non-null   Int64
 9   Goal1Adjective   2054 non-null   object
 10  Pct              2054 non-null   int64
 11  Score            2054 non-null   Int64
dtypes: Int64(2), int64(3), object(7)
memory usage: 196.7+ KB

In [28]:
claim_two['Goal2RitScore'] = claim_two['Goal2RitScore'].astype('Int64')
claim_two = claim_two.dropna(subset=['Goal2RitScore'])
claim_two = claim_two.sort_values(['Goal2RitScore', 'Grade'])
math_melt = math_melt.sort_values(['Score', 'Grade'])
claim_two = pd.merge_asof(claim_two, math_melt, by='Grade', left_on='Goal2RitScore', right_on = 'Score', direction='nearest')
claim_two

C:\Users\derek.castleman\AppData\Local\Temp\ipykernel_31044\1269282662.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  claim_two['Goal2RitScore'] = claim_two['Goal2RitScore'].astype('Int64')

,School,Student ID,Student Name,Grade,LangFlu,SPECIALED Value,Subject,Goal2Name,Goal2RitScore,Goal2Adjective,Pct,Score
0,4,1096422,"Valdivia Santillan, Denisse",K,L,No,Mathematics,Number and Operations,103,Low,1,100
1,4,1096894,"Molina Garcia, Dylan",K,E,No,Mathematics,Number and Operations,104,Low,1,100
2,4,1096747,"Torres, Roselyne",1,E,No,Mathematics,Number and Operations,106,Low,1,100
3,4,1096965,"Perez III Meza, Alfredo",K,L,No,Mathematics,Number and Operations,106,Low,1,100
4,4,1096170,"Leyva, Matthew",1,E,Yes,Mathematics,Number and Operations,111,Low,1,100
...,...,...,...,...,...,...,...,...,...,...,...,...
2050,1,1094006,"Basurto Espino, Raul",11,R,No,Mathematics,The Real and Complex Number Systems,271,High,95,263
2051,4,1094061,"Valenzuela, Anaveya",6,R,No,Mathematics,The Real and Complex Number Systems,276,High,95,237
2052,1,1094856,"Ecijan, Chris Jaren",10,E,No,Mathematics,The Real and Complex Number Systems,280,High,95,257
2053,1,1093759,"Camargo Velasquez, Jocelyn",11,R,No,Mathematics,The Real and Complex Number Systems,280,High,95,263
2054,1,1094876,"Arreola, Saul",11,I,No,Mathematics,The Real and Complex Number Systems,298,High,95,263

In [29]:
claim_three['Goal3RitScore'] = claim_three['Goal3RitScore'].astype('Int64')
claim_three = claim_three.dropna(subset=['Goal3RitScore'])
claim_three = claim_three.sort_values(['Goal3RitScore', 'Grade'])
math_melt = math_melt.sort_values(['Score', 'Grade'])
claim_three = pd.merge_asof(claim_three, math_melt, by='Grade', left_on='Goal3RitScore', right_on = 'Score', direction='nearest')
claim_three

C:\Users\derek.castleman\AppData\Local\Temp\ipykernel_31044\1443689481.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  claim_three['Goal3RitScore'] = claim_three['Goal3RitScore'].astype('Int64')

,School,Student ID,Student Name,Grade,LangFlu,SPECIALED Value,Subject,Goal3Name,Goal3RitScore,Goal3Adjective,Pct,Score
0,4,1096906,"Ramirez Hernandez, Geraldine",K,L,No,Mathematics,Measurement and Data,107,Low,1,100
1,4,1096894,"Molina Garcia, Dylan",K,E,No,Mathematics,Measurement and Data,111,Low,5,121
2,4,1096915,"Silva Flores, Emily",K,L,No,Mathematics,Measurement and Data,113,Low,5,121
3,4,1096611,"Ceja, Ashlynn",K,E,No,Mathematics,Measurement and Data,114,Low,5,121
4,4,1096444,"Rodriguez Nevarez JR, Carlos",K,E,Yes,Mathematics,Measurement and Data,115,Low,5,121
...,...,...,...,...,...,...,...,...,...,...,...,...
2050,1,1095642,"Garcia Torres, Abigail",11,R,No,Mathematics,Geometry,272,High,95,263
2051,1,1093711,"Larios, Anahi",10,I,No,Mathematics,Geometry,274,High,95,257
2052,1,1094856,"Ecijan, Chris Jaren",10,E,No,Mathematics,Geometry,278,High,95,257
2053,1,1094837,"Quintero, Daniel",11,R,No,Mathematics,Geometry,280,High,95,263
2054,1,1094876,"Arreola, Saul",11,I,No,Mathematics,Geometry,285,High,95,263

In [30]:
claim_three.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2055 entries, 0 to 2054
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   School           2055 non-null   int64
 1   Student ID       2055 non-null   int64
 2   Student Name     2055 non-null   object
 3   Grade            2055 non-null   object
 4   LangFlu          2055 non-null   object
 5   SPECIALED Value  2055 non-null   object
 6   Subject          2055 non-null   object
 7   Goal3Name        2055 non-null   object
 8   Goal3RitScore    2055 non-null   Int64
 9   Goal3Adjective   2055 non-null   object
 10  Pct              2055 non-null   int64
 11  Score            2055 non-null   Int64
dtypes: Int64(2), int64(3), object(7)
memory usage: 196.8+ KB

In [31]:
claim_four['Goal4RitScore'] = claim_four['Goal4RitScore'].astype('Int64')
claim_four = claim_four.dropna(subset=['Goal4RitScore'])
claim_four = claim_four.sort_values(['Goal4RitScore', 'Grade'])
math_melt = math_melt.sort_values(['Score', 'Grade'])
claim_four = pd.merge_asof(claim_four, math_melt, by='Grade', left_on='Goal4RitScore', right_on = 'Score', direction='nearest')
claim_four

C:\Users\derek.castleman\AppData\Local\Temp\ipykernel_31044\3972923477.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  claim_four['Goal4RitScore'] = claim_four['Goal4RitScore'].astype('Int64')

,School,Student ID,Student Name,Grade,LangFlu,SPECIALED Value,Subject,Goal4Name,Goal4RitScore,Goal4Adjective,Pct,Score
0,6,1096959,"Hernandez Ibarra, Ximena",1,L,No,Mathematics,Geometry,106,Low,1,100
1,4,1096960,"Hernandez, Mia",K,E,No,Mathematics,Geometry,107,Low,1,100
2,6,1097045,"Carmen Lopez, Alan",K,L,No,Mathematics,Geometry,109,Low,1,100
3,4,1096915,"Silva Flores, Emily",K,L,No,Mathematics,Geometry,109,Low,1,100
4,4,1096432,"Ochoa, Adriel",1,L,No,Mathematics,Geometry,110,Low,1,100
...,...,...,...,...,...,...,...,...,...,...,...,...
2050,8,1093484,"Gutierrez, Tomas",11,E,No,Mathematics,Statistics and Probability,278,High,95,263
2051,1,1094837,"Quintero, Daniel",11,R,No,Mathematics,Statistics and Probability,278,High,95,263
2052,1,1096296,"Manginsay, Joelliane",8,R,No,Mathematics,Statistics and Probability,280,High,95,252
2053,1,1094921,"Verduzco, Aden",11,E,No,Mathematics,Statistics and Probability,280,High,95,263
2054,1,1095013,"Leal, Khristopher",11,R,No,Mathematics,Statistics and Probability,292,High,95,263

In [32]:
# Changes the PCT column to Goal One PCT and drops the extra score from the Math chart
claim_one = claim_one.rename(columns={
    'Pct': 'Goal One PCT'})
claim_one = claim_one.drop('Score', axis=1)
claim_one

,School,Student ID,Student Name,Grade,LangFlu,SPECIALED Value,Subject,Goal1Name,Goal1RitScore,Goal1Adjective,Goal One PCT
0,4,1096895,"Moreno Ruelas, Eliana",K,E,No,Mathematics,Operations and Algebraic Thinking,103,Low,1
1,4,1096961,"Duran, Isaiah",K,E,Yes,Mathematics,Operations and Algebraic Thinking,108,Low,1
2,4,1096867,"Cruz, Juan-David",K,E,Yes,Mathematics,Operations and Algebraic Thinking,110,Low,1
3,4,1096960,"Hernandez, Mia",K,E,No,Mathematics,Operations and Algebraic Thinking,110,Low,1
4,4,1096899,"Pacheco, Aytana",K,E,No,Mathematics,Operations and Algebraic Thinking,110,Low,1
...,...,...,...,...,...,...,...,...,...,...,...
2049,8,1092547,"Rodriguez Almanza, Alexander",10,R,No,Mathematics,Operations and Algebraic Thinking,272,High,95
2050,1,1097001,"Moffett, Levi",9,E,No,Mathematics,Operations and Algebraic Thinking,274,High,95
2051,1,1094305,"Rodriguez, Fatima",10,R,No,Mathematics,Operations and Algebraic Thinking,276,High,95
2052,1,1093057,"Mercado, Natalie",11,E,No,Mathematics,Operations and Algebraic Thinking,278,High,95
2053,1,1094876,"Arreola, Saul",11,I,No,Mathematics,Operations and Algebraic Thinking,285,High,95

In [33]:
claim_two = claim_two.rename(columns={
    'Pct': 'Goal Two PCT'})
claim_two = claim_two.drop('Score', axis=1)
claim_two

,School,Student ID,Student Name,Grade,LangFlu,SPECIALED Value,Subject,Goal2Name,Goal2RitScore,Goal2Adjective,Goal Two PCT
0,4,1096422,"Valdivia Santillan, Denisse",K,L,No,Mathematics,Number and Operations,103,Low,1
1,4,1096894,"Molina Garcia, Dylan",K,E,No,Mathematics,Number and Operations,104,Low,1
2,4,1096747,"Torres, Roselyne",1,E,No,Mathematics,Number and Operations,106,Low,1
3,4,1096965,"Perez III Meza, Alfredo",K,L,No,Mathematics,Number and Operations,106,Low,1
4,4,1096170,"Leyva, Matthew",1,E,Yes,Mathematics,Number and Operations,111,Low,1
...,...,...,...,...,...,...,...,...,...,...,...
2050,1,1094006,"Basurto Espino, Raul",11,R,No,Mathematics,The Real and Complex Number Systems,271,High,95
2051,4,1094061,"Valenzuela, Anaveya",6,R,No,Mathematics,The Real and Complex Number Systems,276,High,95
2052,1,1094856,"Ecijan, Chris Jaren",10,E,No,Mathematics,The Real and Complex Number Systems,280,High,95
2053,1,1093759,"Camargo Velasquez, Jocelyn",11,R,No,Mathematics,The Real and Complex Number Systems,280,High,95
2054,1,1094876,"Arreola, Saul",11,I,No,Mathematics,The Real and Complex Number Systems,298,High,95

In [34]:
claim_three = claim_three.rename(columns={
    'Pct': 'Goal Three PCT'})
claim_three = claim_three.drop('Score', axis=1)
claim_three

,School,Student ID,Student Name,Grade,LangFlu,SPECIALED Value,Subject,Goal3Name,Goal3RitScore,Goal3Adjective,Goal Three PCT
0,4,1096906,"Ramirez Hernandez, Geraldine",K,L,No,Mathematics,Measurement and Data,107,Low,1
1,4,1096894,"Molina Garcia, Dylan",K,E,No,Mathematics,Measurement and Data,111,Low,5
2,4,1096915,"Silva Flores, Emily",K,L,No,Mathematics,Measurement and Data,113,Low,5
3,4,1096611,"Ceja, Ashlynn",K,E,No,Mathematics,Measurement and Data,114,Low,5
4,4,1096444,"Rodriguez Nevarez JR, Carlos",K,E,Yes,Mathematics,Measurement and Data,115,Low,5
...,...,...,...,...,...,...,...,...,...,...,...
2050,1,1095642,"Garcia Torres, Abigail",11,R,No,Mathematics,Geometry,272,High,95
2051,1,1093711,"Larios, Anahi",10,I,No,Mathematics,Geometry,274,High,95
2052,1,1094856,"Ecijan, Chris Jaren",10,E,No,Mathematics,Geometry,278,High,95
2053,1,1094837,"Quintero, Daniel",11,R,No,Mathematics,Geometry,280,High,95
2054,1,1094876,"Arreola, Saul",11,I,No,Mathematics,Geometry,285,High,95

In [35]:
claim_four = claim_four.rename(columns={
    'Pct': 'Goal Four PCT'})
claim_four = claim_four.drop('Score', axis=1)
claim_four

,School,Student ID,Student Name,Grade,LangFlu,SPECIALED Value,Subject,Goal4Name,Goal4RitScore,Goal4Adjective,Goal Four PCT
0,6,1096959,"Hernandez Ibarra, Ximena",1,L,No,Mathematics,Geometry,106,Low,1
1,4,1096960,"Hernandez, Mia",K,E,No,Mathematics,Geometry,107,Low,1
2,6,1097045,"Carmen Lopez, Alan",K,L,No,Mathematics,Geometry,109,Low,1
3,4,1096915,"Silva Flores, Emily",K,L,No,Mathematics,Geometry,109,Low,1
4,4,1096432,"Ochoa, Adriel",1,L,No,Mathematics,Geometry,110,Low,1
...,...,...,...,...,...,...,...,...,...,...,...
2050,8,1093484,"Gutierrez, Tomas",11,E,No,Mathematics,Statistics and Probability,278,High,95
2051,1,1094837,"Quintero, Daniel",11,R,No,Mathematics,Statistics and Probability,278,High,95
2052,1,1096296,"Manginsay, Joelliane",8,R,No,Mathematics,Statistics and Probability,280,High,95
2053,1,1094921,"Verduzco, Aden",11,E,No,Mathematics,Statistics and Probability,280,High,95
2054,1,1095013,"Leal, Khristopher",11,R,No,Mathematics,Statistics and Probability,292,High,95

In [36]:
# Merge claim one with claim two to start rebuilding Math data frame
math = pd.merge(claim_one, claim_two, how='outer', on=['School', 'Student ID', 'Student Name', 'Grade', 'LangFlu', 'SPECIALED Value', 'Subject'])
math

,School,Student ID,Student Name,Grade,LangFlu,SPECIALED Value,Subject,Goal1Name,Goal1RitScore,Goal1Adjective,Goal One PCT,Goal2Name,Goal2RitScore,Goal2Adjective,Goal Two PCT
0,1,1092314,"Garcia, Isaias",8,L,Yes,Mathematics,Operations and Algebraic Thinking,189,Low,5.0,The Real and Complex Number Systems,189,Low,5.0
1,1,1092319,"Nunez Rodriguez, Stephanie",8,R,No,Mathematics,Operations and Algebraic Thinking,241,High,85.0,The Real and Complex Number Systems,238,High,80.0
2,1,1092320,"Ragudo, Devin Maddox",8,E,No,Mathematics,Operations and Algebraic Thinking,241,High,85.0,The Real and Complex Number Systems,255,High,95.0
3,1,1092327,"De Hoyos, Valentina",8,R,No,Mathematics,Operations and Algebraic Thinking,239,High,80.0,The Real and Complex Number Systems,251,High,95.0
4,1,1092329,"Bragg, Haley",8,E,No,Mathematics,Operations and Algebraic Thinking,244,High,90.0,The Real and Complex Number Systems,251,High,95.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2051,8,1096945,"Martinez Maravilla, Juliana",8,R,No,Mathematics,Operations and Algebraic Thinking,210,LoAvg,25.0,The Real and Complex Number Systems,204,Low,15.0
2052,8,1096967,"Ruiz, Gustavo",7,E,No,Mathematics,Operations and Algebraic Thinking,211,LoAvg,35.0,The Real and Complex Number Systems,197,Low,10.0
2053,8,1096988,"Carranza Mendoza, Katie",8,L,No,Mathematics,Operations and Algebraic Thinking,211,LoAvg,25.0,The Real and Complex Number Systems,206,Low,20.0
2054,8,1097021,"Barrera, Brianna",10,L,No,Mathematics,Operations and Algebraic Thinking,217,LoAvg,30.0,The Real and Complex Number Systems,209,Low,15.0
2055,999,1095414,"Rosales, Estela",5,L,No,Mathematics,Operations and Algebraic Thinking,170,Low,5.0,Number and Operations,203,Avg,40.0

In [37]:
math = pd.merge(math, claim_three, how='outer', on=['School', 'Student ID', 'Student Name', 'Grade', 'LangFlu', 'SPECIALED Value', 'Subject'])
math

,School,Student ID,Student Name,Grade,LangFlu,SPECIALED Value,Subject,Goal1Name,Goal1RitScore,Goal1Adjective,Goal One PCT,Goal2Name,Goal2RitScore,Goal2Adjective,Goal Two PCT,Goal3Name,Goal3RitScore,Goal3Adjective,Goal Three PCT
0,1,1092314,"Garcia, Isaias",8,L,Yes,Mathematics,Operations and Algebraic Thinking,189,Low,5.0,The Real and Complex Number Systems,189,Low,5.0,Geometry,201,Low,10.0
1,1,1092319,"Nunez Rodriguez, Stephanie",8,R,No,Mathematics,Operations and Algebraic Thinking,241,High,85.0,The Real and Complex Number Systems,238,High,80.0,Geometry,230,HiAvg,65.0
2,1,1092320,"Ragudo, Devin Maddox",8,E,No,Mathematics,Operations and Algebraic Thinking,241,High,85.0,The Real and Complex Number Systems,255,High,95.0,Geometry,243,High,85.0
3,1,1092327,"De Hoyos, Valentina",8,R,No,Mathematics,Operations and Algebraic Thinking,239,High,80.0,The Real and Complex Number Systems,251,High,95.0,Geometry,239,High,80.0
4,1,1092329,"Bragg, Haley",8,E,No,Mathematics,Operations and Algebraic Thinking,244,High,90.0,The Real and Complex Number Systems,251,High,95.0,Geometry,241,High,85.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2051,8,1096945,"Martinez Maravilla, Juliana",8,R,No,Mathematics,Operations and Algebraic Thinking,210,LoAvg,25.0,The Real and Complex Number Systems,204,Low,15.0,Geometry,208,LoAvg,20.0
2052,8,1096967,"Ruiz, Gustavo",7,E,No,Mathematics,Operations and Algebraic Thinking,211,LoAvg,35.0,The Real and Complex Number Systems,197,Low,10.0,Geometry,191,Low,5.0
2053,8,1096988,"Carranza Mendoza, Katie",8,L,No,Mathematics,Operations and Algebraic Thinking,211,LoAvg,25.0,The Real and Complex Number Systems,206,Low,20.0,Geometry,199,Low,10.0
2054,8,1097021,"Barrera, Brianna",10,L,No,Mathematics,Operations and Algebraic Thinking,217,LoAvg,30.0,The Real and Complex Number Systems,209,Low,15.0,Geometry,215,LoAvg,25.0
2055,999,1095414,"Rosales, Estela",5,L,No,Mathematics,Operations and Algebraic Thinking,170,Low,5.0,Number and Operations,203,Avg,40.0,Measurement and Data,175,Low,5.0

In [38]:
math = pd.merge(math, claim_four, how='outer', on=['School', 'Student ID', 'Student Name', 'Grade', 'LangFlu', 'SPECIALED Value', 'Subject'])
math

,School,Student ID,Student Name,Grade,LangFlu,SPECIALED Value,Subject,Goal1Name,Goal1RitScore,Goal1Adjective,...,Goal2Adjective,Goal Two PCT,Goal3Name,Goal3RitScore,Goal3Adjective,Goal Three PCT,Goal4Name,Goal4RitScore,Goal4Adjective,Goal Four PCT
0,1,1092314,"Garcia, Isaias",8,L,Yes,Mathematics,Operations and Algebraic Thinking,189,Low,...,Low,5.0,Geometry,201,Low,10.0,Statistics and Probability,196,Low,10.0
1,1,1092319,"Nunez Rodriguez, Stephanie",8,R,No,Mathematics,Operations and Algebraic Thinking,241,High,...,High,80.0,Geometry,230,HiAvg,65.0,Statistics and Probability,212,LoAvg,30.0
2,1,1092320,"Ragudo, Devin Maddox",8,E,No,Mathematics,Operations and Algebraic Thinking,241,High,...,High,95.0,Geometry,243,High,85.0,Statistics and Probability,250,High,95.0
3,1,1092327,"De Hoyos, Valentina",8,R,No,Mathematics,Operations and Algebraic Thinking,239,High,...,High,95.0,Geometry,239,High,80.0,Statistics and Probability,239,High,80.0
4,1,1092329,"Bragg, Haley",8,E,No,Mathematics,Operations and Algebraic Thinking,244,High,...,High,95.0,Geometry,241,High,85.0,Statistics and Probability,240,High,85.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2051,8,1096945,"Martinez Maravilla, Juliana",8,R,No,Mathematics,Operations and Algebraic Thinking,210,LoAvg,...,Low,15.0,Geometry,208,LoAvg,20.0,Statistics and Probability,231,HiAvg,70.0
2052,8,1096967,"Ruiz, Gustavo",7,E,No,Mathematics,Operations and Algebraic Thinking,211,LoAvg,...,Low,10.0,Geometry,191,Low,5.0,Statistics and Probability,196,Low,10.0
2053,8,1096988,"Carranza Mendoza, Katie",8,L,No,Mathematics,Operations and Algebraic Thinking,211,LoAvg,...,Low,20.0,Geometry,199,Low,10.0,Statistics and Probability,225,Avg,55.0
2054,8,1097021,"Barrera, Brianna",10,L,No,Mathematics,Operations and Algebraic Thinking,217,LoAvg,...,Low,15.0,Geometry,215,LoAvg,25.0,Statistics and Probability,207,Low,15.0
2055,999,1095414,"Rosales, Estela",5,L,No,Mathematics,Operations and Algebraic Thinking,170,Low,...,Avg,40.0,Measurement and Data,175,Low,5.0,Geometry,189,Low,15.0

### ELA

Everything that was done with the Math portion of the test will be duplicated once again but now for the ELA portion of the test.

In [39]:
ela = pd.merge(roster, ela_columns, how='inner', left_on='Student ID', right_on='StudentID')
ela

,School,Student ID,Student Name,Grade,LangFlu,SPECIALED Value,StudentID,Subject,Goal1Name,Goal1RitScore,Goal1Adjective,Goal2Name,Goal2RitScore,Goal2Adjective,Goal3Name,Goal3RitScore,Goal3Adjective,Goal4Name,Goal4RitScore,Goal4Adjective
0,1,1094167,"Aaron, Anastasia",7,E,No,1094167,Language Arts,Literary Text,206.0,LoAvg,Informational Text,207.0,LoAvg,Vocabulary,207.0,LoAvg,NaN,NaN,NaN
1,4,1095258,"Aaron, Lillie",4,E,No,1095258,Language Arts,Literary Text,200.0,Avg,Informational Text,195.0,Avg,Vocabulary,199.0,Avg,NaN,NaN,NaN
2,4,1096128,"Aburto-Ramirez, Anaiah",2,L,No,1096128,Language Arts,Literary Text,148.0,Low,Informational Text,157.0,LoAvg,Vocabulary,155.0,Low,NaN,NaN,NaN
3,4,1093925,"Aburto-Ramirez, Ayden",5,L,No,1093925,Language Arts,Literary Text,218.0,HiAvg,Informational Text,211.0,HiAvg,Vocabulary,200.0,Avg,NaN,NaN,NaN
4,4,1096854,"Abuyen, Jhene",K,E,No,1096854,Language Arts,Foundational Skills,129.0,Low,Language and Writing,138.0,Avg,Literature and Informational Text,127.0,Low,Vocabulary Use and Functions,138.0,Avg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2054,4,1096922,"Zepeda Salas, Francisco",K,E,No,1096922,Language Arts,Foundational Skills,129.0,Low,Language and Writing,147.0,High,Literature and Informational Text,131.0,LoAvg,Vocabulary Use and Functions,148.0,High
2055,6,1095271,"Zuniga, Alan",4,L,No,1095271,Language Arts,Literary Text,182.0,LoAvg,Informational Text,188.0,LoAvg,Vocabulary,185.0,LoAvg,NaN,NaN,NaN
2056,8,1092848,"Zuniga, Michelle",8,R,No,1092848,Language Arts,Literary Text,230.0,HiAvg,Informational Text,230.0,HiAvg,Vocabulary,222.0,HiAvg,NaN,NaN,NaN
2057,6,1096578,"Zuniga, Zoe",1,E,No,1096578,Language Arts,Foundational Skills,140.0,Low,Language and Writing,122.0,Low,Literature and Informational Text,144.0,Low,Vocabulary Use and Functions,123.0,Low
2058,6,1094375,"Zuniga Vazquez, Luis",6,R,No,1094375,Language Arts,Literary Text,213.0,Avg,Informational Text,215.0,HiAvg,Vocabulary,221.0,HiAvg,NaN,NaN,NaN

In [40]:
claim_one = ela.iloc[:, [0, 1, 2, 3, 4, 5, 7, 8, 9, 10]]
claim_one

,School,Student ID,Student Name,Grade,LangFlu,SPECIALED Value,Subject,Goal1Name,Goal1RitScore,Goal1Adjective
0,1,1094167,"Aaron, Anastasia",7,E,No,Language Arts,Literary Text,206.0,LoAvg
1,4,1095258,"Aaron, Lillie",4,E,No,Language Arts,Literary Text,200.0,Avg
2,4,1096128,"Aburto-Ramirez, Anaiah",2,L,No,Language Arts,Literary Text,148.0,Low
3,4,1093925,"Aburto-Ramirez, Ayden",5,L,No,Language Arts,Literary Text,218.0,HiAvg
4,4,1096854,"Abuyen, Jhene",K,E,No,Language Arts,Foundational Skills,129.0,Low
...,...,...,...,...,...,...,...,...,...,...
2054,4,1096922,"Zepeda Salas, Francisco",K,E,No,Language Arts,Foundational Skills,129.0,Low
2055,6,1095271,"Zuniga, Alan",4,L,No,Language Arts,Literary Text,182.0,LoAvg
2056,8,1092848,"Zuniga, Michelle",8,R,No,Language Arts,Literary Text,230.0,HiAvg
2057,6,1096578,"Zuniga, Zoe",1,E,No,Language Arts,Foundational Skills,140.0,Low
2058,6,1094375,"Zuniga Vazquez, Luis",6,R,No,Language Arts,Literary Text,213.0,Avg

In [41]:
claim_two = ela.iloc[:, [0, 1, 2, 3, 4, 5, 7, 11, 12, 13]]
claim_two

,School,Student ID,Student Name,Grade,LangFlu,SPECIALED Value,Subject,Goal2Name,Goal2RitScore,Goal2Adjective
0,1,1094167,"Aaron, Anastasia",7,E,No,Language Arts,Informational Text,207.0,LoAvg
1,4,1095258,"Aaron, Lillie",4,E,No,Language Arts,Informational Text,195.0,Avg
2,4,1096128,"Aburto-Ramirez, Anaiah",2,L,No,Language Arts,Informational Text,157.0,LoAvg
3,4,1093925,"Aburto-Ramirez, Ayden",5,L,No,Language Arts,Informational Text,211.0,HiAvg
4,4,1096854,"Abuyen, Jhene",K,E,No,Language Arts,Language and Writing,138.0,Avg
...,...,...,...,...,...,...,...,...,...,...
2054,4,1096922,"Zepeda Salas, Francisco",K,E,No,Language Arts,Language and Writing,147.0,High
2055,6,1095271,"Zuniga, Alan",4,L,No,Language Arts,Informational Text,188.0,LoAvg
2056,8,1092848,"Zuniga, Michelle",8,R,No,Language Arts,Informational Text,230.0,HiAvg
2057,6,1096578,"Zuniga, Zoe",1,E,No,Language Arts,Language and Writing,122.0,Low
2058,6,1094375,"Zuniga Vazquez, Luis",6,R,No,Language Arts,Informational Text,215.0,HiAvg

In [42]:
claim_three = ela.iloc[:, [0, 1, 2, 3, 4, 5, 7, 14, 15, 16]]
claim_three

,School,Student ID,Student Name,Grade,LangFlu,SPECIALED Value,Subject,Goal3Name,Goal3RitScore,Goal3Adjective
0,1,1094167,"Aaron, Anastasia",7,E,No,Language Arts,Vocabulary,207.0,LoAvg
1,4,1095258,"Aaron, Lillie",4,E,No,Language Arts,Vocabulary,199.0,Avg
2,4,1096128,"Aburto-Ramirez, Anaiah",2,L,No,Language Arts,Vocabulary,155.0,Low
3,4,1093925,"Aburto-Ramirez, Ayden",5,L,No,Language Arts,Vocabulary,200.0,Avg
4,4,1096854,"Abuyen, Jhene",K,E,No,Language Arts,Literature and Informational Text,127.0,Low
...,...,...,...,...,...,...,...,...,...,...
2054,4,1096922,"Zepeda Salas, Francisco",K,E,No,Language Arts,Literature and Informational Text,131.0,LoAvg
2055,6,1095271,"Zuniga, Alan",4,L,No,Language Arts,Vocabulary,185.0,LoAvg
2056,8,1092848,"Zuniga, Michelle",8,R,No,Language Arts,Vocabulary,222.0,HiAvg
2057,6,1096578,"Zuniga, Zoe",1,E,No,Language Arts,Literature and Informational Text,144.0,Low
2058,6,1094375,"Zuniga Vazquez, Luis",6,R,No,Language Arts,Vocabulary,221.0,HiAvg

In [43]:
claim_four = ela.iloc[:, [0, 1, 2, 3, 4, 5, 7, 17, 18, 19]]
claim_four

,School,Student ID,Student Name,Grade,LangFlu,SPECIALED Value,Subject,Goal4Name,Goal4RitScore,Goal4Adjective
0,1,1094167,"Aaron, Anastasia",7,E,No,Language Arts,NaN,NaN,NaN
1,4,1095258,"Aaron, Lillie",4,E,No,Language Arts,NaN,NaN,NaN
2,4,1096128,"Aburto-Ramirez, Anaiah",2,L,No,Language Arts,NaN,NaN,NaN
3,4,1093925,"Aburto-Ramirez, Ayden",5,L,No,Language Arts,NaN,NaN,NaN
4,4,1096854,"Abuyen, Jhene",K,E,No,Language Arts,Vocabulary Use and Functions,138.0,Avg
...,...,...,...,...,...,...,...,...,...,...
2054,4,1096922,"Zepeda Salas, Francisco",K,E,No,Language Arts,Vocabulary Use and Functions,148.0,High
2055,6,1095271,"Zuniga, Alan",4,L,No,Language Arts,NaN,NaN,NaN
2056,8,1092848,"Zuniga, Michelle",8,R,No,Language Arts,NaN,NaN,NaN
2057,6,1096578,"Zuniga, Zoe",1,E,No,Language Arts,Vocabulary Use and Functions,123.0,Low
2058,6,1094375,"Zuniga Vazquez, Luis",6,R,No,Language Arts,NaN,NaN,NaN

In [44]:
ela_melt['Score'] = ela_melt['Score'].astype('Int64')
ela_melt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 273 entries, 0 to 272
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Pct     273 non-null    int64
 1   Grade   273 non-null    object
 2   Score   273 non-null    Int64
dtypes: Int64(1), int64(1), object(1)
memory usage: 6.8+ KB

In [45]:
claim_one.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2059 entries, 0 to 2058
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   School           2059 non-null   int64
 1   Student ID       2059 non-null   int64
 2   Student Name     2059 non-null   object
 3   Grade            2059 non-null   object
 4   LangFlu          2059 non-null   object
 5   SPECIALED Value  2059 non-null   object
 6   Subject          2059 non-null   object
 7   Goal1Name        2059 non-null   object
 8   Goal1RitScore    2057 non-null   float64
 9   Goal1Adjective   2057 non-null   object
dtypes: float64(1), int64(2), object(7)
memory usage: 161.0+ KB

In [46]:
claim_one['Goal1RitScore'] = claim_one['Goal1RitScore'].astype('Int64')
claim_one = claim_one.dropna(subset=['Goal1RitScore'])
claim_one = claim_one.sort_values(['Goal1RitScore', 'Grade'])
ela_melt = ela_melt.sort_values(['Score', 'Grade'])
claim_one = pd.merge_asof(claim_one, ela_melt, by='Grade', left_on='Goal1RitScore', right_on = 'Score', direction='nearest')
claim_one

C:\Users\derek.castleman\AppData\Local\Temp\ipykernel_31044\991983597.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  claim_one['Goal1RitScore'] = claim_one['Goal1RitScore'].astype('Int64')

,School,Student ID,Student Name,Grade,LangFlu,SPECIALED Value,Subject,Goal1Name,Goal1RitScore,Goal1Adjective,Pct,Score
0,4,1096904,"Pulido Nunez, Bruno",K,L,No,Language Arts,Foundational Skills,101,Low,1,100
1,4,1096860,"Basurto Camacho, Jazleen",K,L,No,Language Arts,Foundational Skills,109,Low,1,100
2,4,1096914,"Santoyo Zendejas, Alexzander",K,L,No,Language Arts,Foundational Skills,109,Low,1,100
3,4,1096955,"Barajas, Saul",K,L,Yes,Language Arts,Foundational Skills,112,Low,1,100
4,4,1096897,"Nunez, Ismael",K,E,No,Language Arts,Foundational Skills,112,Low,1,100
...,...,...,...,...,...,...,...,...,...,...,...,...
2052,1,1092943,"Barreto, Jeniah",8,R,No,Language Arts,Literary Text,253,High,95,228
2053,8,1092847,"Cruz, Angel",10,R,No,Language Arts,Literary Text,256,High,95,232
2054,1,1094090,"Stevens, Michael",11,E,No,Language Arts,Literary Text,259,High,95,233
2055,1,1093024,"Serna, Love",10,E,No,Language Arts,Literary Text,261,High,95,232
2056,8,1093484,"Gutierrez, Tomas",11,E,No,Language Arts,Literary Text,269,High,95,233

In [47]:
claim_one.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2057 entries, 0 to 2056
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   School           2057 non-null   int64
 1   Student ID       2057 non-null   int64
 2   Student Name     2057 non-null   object
 3   Grade            2057 non-null   object
 4   LangFlu          2057 non-null   object
 5   SPECIALED Value  2057 non-null   object
 6   Subject          2057 non-null   object
 7   Goal1Name        2057 non-null   object
 8   Goal1RitScore    2057 non-null   Int64
 9   Goal1Adjective   2057 non-null   object
 10  Pct              2057 non-null   int64
 11  Score            2057 non-null   Int64
dtypes: Int64(2), int64(3), object(7)
memory usage: 197.0+ KB

In [48]:
claim_two['Goal2RitScore'] = claim_two['Goal2RitScore'].astype('Int64')
claim_two = claim_two.dropna(subset=['Goal2RitScore'])
claim_two = claim_two.sort_values(['Goal2RitScore', 'Grade'])
ela_melt = ela_melt.sort_values(['Score', 'Grade'])
claim_two = pd.merge_asof(claim_two, ela_melt, by='Grade', left_on='Goal2RitScore', right_on = 'Score', direction='nearest')
claim_two

C:\Users\derek.castleman\AppData\Local\Temp\ipykernel_31044\10343301.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  claim_two['Goal2RitScore'] = claim_two['Goal2RitScore'].astype('Int64')

,School,Student ID,Student Name,Grade,LangFlu,SPECIALED Value,Subject,Goal2Name,Goal2RitScore,Goal2Adjective,Pct,Score
0,4,1096899,"Pacheco, Aytana",K,E,No,Language Arts,Language and Writing,101,Low,1,100
1,4,1096867,"Cruz, Juan-David",K,E,Yes,Language Arts,Language and Writing,110,Low,1,100
2,4,1096897,"Nunez, Ismael",K,E,No,Language Arts,Language and Writing,111,Low,1,100
3,4,1096920,"Vizcarra, Saint",K,E,No,Language Arts,Language and Writing,111,Low,1,100
4,4,1096915,"Silva Flores, Emily",K,L,No,Language Arts,Language and Writing,114,Low,1,100
...,...,...,...,...,...,...,...,...,...,...,...,...
2053,1,1093024,"Serna, Love",10,E,No,Language Arts,Informational Text,250,High,95,232
2054,1,1094081,"Gutierrez, Saray",11,R,No,Language Arts,Informational Text,250,High,95,233
2055,1,1093053,"Lara Zambrano, Jonathan",11,R,No,Language Arts,Informational Text,250,High,95,233
2056,1,1094086,"Valdez Gutierrez, Carlos",11,E,No,Language Arts,Informational Text,250,High,95,233
2057,1,1094006,"Basurto Espino, Raul",11,R,No,Language Arts,Informational Text,262,High,95,233

In [49]:
claim_three['Goal3RitScore'] = claim_three['Goal3RitScore'].astype('Int64')
claim_three = claim_three.dropna(subset=['Goal3RitScore'])
claim_three = claim_three.sort_values(['Goal3RitScore', 'Grade'])
ela_melt = ela_melt.sort_values(['Score', 'Grade'])
claim_three = pd.merge_asof(claim_three, ela_melt, by='Grade', left_on='Goal3RitScore', right_on = 'Score', direction='nearest')
claim_three

C:\Users\derek.castleman\AppData\Local\Temp\ipykernel_31044\1268706847.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  claim_three['Goal3RitScore'] = claim_three['Goal3RitScore'].astype('Int64')

,School,Student ID,Student Name,Grade,LangFlu,SPECIALED Value,Subject,Goal3Name,Goal3RitScore,Goal3Adjective,Pct,Score
0,4,1096955,"Barajas, Saul",K,L,Yes,Language Arts,Literature and Informational Text,102,Low,1,100
1,4,1096867,"Cruz, Juan-David",K,E,Yes,Language Arts,Literature and Informational Text,106,Low,1,100
2,4,1096858,"Alegria Herrera, Matthew",K,L,No,Language Arts,Literature and Informational Text,114,Low,1,100
3,4,1096612,"Lopez, Elliana",K,E,No,Language Arts,Literature and Informational Text,114,Low,1,100
4,4,1096897,"Nunez, Ismael",K,E,No,Language Arts,Literature and Informational Text,115,Low,1,100
...,...,...,...,...,...,...,...,...,...,...,...,...
2053,1,1093893,"Cardoza, Isaac",9,R,No,Language Arts,Vocabulary,259,High,95,230
2054,8,1093471,"Mendez Sanchez, Karina",11,R,No,Language Arts,Vocabulary,259,High,95,233
2055,1,1093996,"Madueno Carranza, Leslie",11,R,No,Language Arts,Vocabulary,261,High,95,233
2056,1,1094837,"Quintero, Daniel",11,R,No,Language Arts,Vocabulary,262,High,95,233
2057,1,1094876,"Arreola, Saul",11,I,No,Language Arts,Vocabulary,263,High,95,233

In [50]:
claim_three.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2058 entries, 0 to 2057
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   School           2058 non-null   int64
 1   Student ID       2058 non-null   int64
 2   Student Name     2058 non-null   object
 3   Grade            2058 non-null   object
 4   LangFlu          2058 non-null   object
 5   SPECIALED Value  2058 non-null   object
 6   Subject          2058 non-null   object
 7   Goal3Name        2058 non-null   object
 8   Goal3RitScore    2058 non-null   Int64
 9   Goal3Adjective   2058 non-null   object
 10  Pct              2058 non-null   int64
 11  Score            2058 non-null   Int64
dtypes: Int64(2), int64(3), object(7)
memory usage: 197.1+ KB

In [51]:
claim_four['Goal4RitScore'] = claim_four['Goal4RitScore'].astype('Int64')
claim_four = claim_four.dropna(subset=['Goal4RitScore'])
claim_four = claim_four.sort_values(['Goal4RitScore', 'Grade'])
ela_melt = ela_melt.sort_values(['Score', 'Grade'])
claim_four = pd.merge_asof(claim_four, ela_melt, by='Grade', left_on='Goal4RitScore', right_on = 'Score', direction='nearest')
claim_four

C:\Users\derek.castleman\AppData\Local\Temp\ipykernel_31044\2327905000.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  claim_four['Goal4RitScore'] = claim_four['Goal4RitScore'].astype('Int64')

,School,Student ID,Student Name,Grade,LangFlu,SPECIALED Value,Subject,Goal4Name,Goal4RitScore,Goal4Adjective,Pct,Score
0,6,1096561,"Mendez Juarez, Ximena",K,L,No,Language Arts,Vocabulary Use and Functions,102,Low,1,100
1,4,1096990,"Enriquez Lopez, Clarissa",K,L,No,Language Arts,Vocabulary Use and Functions,103,Low,1,100
2,4,1096444,"Rodriguez Nevarez JR, Carlos",K,E,Yes,Language Arts,Vocabulary Use and Functions,109,Low,1,100
3,4,1096955,"Barajas, Saul",K,L,Yes,Language Arts,Vocabulary Use and Functions,110,Low,1,100
4,6,1097045,"Carmen Lopez, Alan",K,L,No,Language Arts,Vocabulary Use and Functions,110,Low,1,100
...,...,...,...,...,...,...,...,...,...,...,...,...
294,6,1096295,"Rodriguez Almanza, Jessica",1,I,No,Language Arts,Vocabulary Use and Functions,183,High,95,165
295,4,1096497,"Medina, Katherine",1,E,No,Language Arts,Vocabulary Use and Functions,184,High,95,165
296,4,1096689,"Fernandez, Liam",1,E,Yes,Language Arts,Vocabulary Use and Functions,190,High,95,165
297,4,1096524,"Grewal, Armaan",1,E,No,Language Arts,Vocabulary Use and Functions,191,High,95,165
298,4,1096479,"Bejarano, Cassiopeia",1,E,No,Language Arts,Vocabulary Use and Functions,205,High,95,165

In [52]:
claim_one = claim_one.rename(columns={
    'Pct': 'Goal One PCT'})
claim_one = claim_one.drop('Score', axis=1)
claim_one

,School,Student ID,Student Name,Grade,LangFlu,SPECIALED Value,Subject,Goal1Name,Goal1RitScore,Goal1Adjective,Goal One PCT
0,4,1096904,"Pulido Nunez, Bruno",K,L,No,Language Arts,Foundational Skills,101,Low,1
1,4,1096860,"Basurto Camacho, Jazleen",K,L,No,Language Arts,Foundational Skills,109,Low,1
2,4,1096914,"Santoyo Zendejas, Alexzander",K,L,No,Language Arts,Foundational Skills,109,Low,1
3,4,1096955,"Barajas, Saul",K,L,Yes,Language Arts,Foundational Skills,112,Low,1
4,4,1096897,"Nunez, Ismael",K,E,No,Language Arts,Foundational Skills,112,Low,1
...,...,...,...,...,...,...,...,...,...,...,...
2052,1,1092943,"Barreto, Jeniah",8,R,No,Language Arts,Literary Text,253,High,95
2053,8,1092847,"Cruz, Angel",10,R,No,Language Arts,Literary Text,256,High,95
2054,1,1094090,"Stevens, Michael",11,E,No,Language Arts,Literary Text,259,High,95
2055,1,1093024,"Serna, Love",10,E,No,Language Arts,Literary Text,261,High,95
2056,8,1093484,"Gutierrez, Tomas",11,E,No,Language Arts,Literary Text,269,High,95

In [53]:
claim_two = claim_two.rename(columns={
    'Pct': 'Goal Two PCT'})
claim_two = claim_two.drop('Score', axis=1)
claim_two

,School,Student ID,Student Name,Grade,LangFlu,SPECIALED Value,Subject,Goal2Name,Goal2RitScore,Goal2Adjective,Goal Two PCT
0,4,1096899,"Pacheco, Aytana",K,E,No,Language Arts,Language and Writing,101,Low,1
1,4,1096867,"Cruz, Juan-David",K,E,Yes,Language Arts,Language and Writing,110,Low,1
2,4,1096897,"Nunez, Ismael",K,E,No,Language Arts,Language and Writing,111,Low,1
3,4,1096920,"Vizcarra, Saint",K,E,No,Language Arts,Language and Writing,111,Low,1
4,4,1096915,"Silva Flores, Emily",K,L,No,Language Arts,Language and Writing,114,Low,1
...,...,...,...,...,...,...,...,...,...,...,...
2053,1,1093024,"Serna, Love",10,E,No,Language Arts,Informational Text,250,High,95
2054,1,1094081,"Gutierrez, Saray",11,R,No,Language Arts,Informational Text,250,High,95
2055,1,1093053,"Lara Zambrano, Jonathan",11,R,No,Language Arts,Informational Text,250,High,95
2056,1,1094086,"Valdez Gutierrez, Carlos",11,E,No,Language Arts,Informational Text,250,High,95
2057,1,1094006,"Basurto Espino, Raul",11,R,No,Language Arts,Informational Text,262,High,95

In [54]:
claim_three = claim_three.rename(columns={
    'Pct': 'Goal Three PCT'})
claim_three = claim_three.drop('Score', axis=1)
claim_three

,School,Student ID,Student Name,Grade,LangFlu,SPECIALED Value,Subject,Goal3Name,Goal3RitScore,Goal3Adjective,Goal Three PCT
0,4,1096955,"Barajas, Saul",K,L,Yes,Language Arts,Literature and Informational Text,102,Low,1
1,4,1096867,"Cruz, Juan-David",K,E,Yes,Language Arts,Literature and Informational Text,106,Low,1
2,4,1096858,"Alegria Herrera, Matthew",K,L,No,Language Arts,Literature and Informational Text,114,Low,1
3,4,1096612,"Lopez, Elliana",K,E,No,Language Arts,Literature and Informational Text,114,Low,1
4,4,1096897,"Nunez, Ismael",K,E,No,Language Arts,Literature and Informational Text,115,Low,1
...,...,...,...,...,...,...,...,...,...,...,...
2053,1,1093893,"Cardoza, Isaac",9,R,No,Language Arts,Vocabulary,259,High,95
2054,8,1093471,"Mendez Sanchez, Karina",11,R,No,Language Arts,Vocabulary,259,High,95
2055,1,1093996,"Madueno Carranza, Leslie",11,R,No,Language Arts,Vocabulary,261,High,95
2056,1,1094837,"Quintero, Daniel",11,R,No,Language Arts,Vocabulary,262,High,95
2057,1,1094876,"Arreola, Saul",11,I,No,Language Arts,Vocabulary,263,High,95

In [55]:
claim_four = claim_four.rename(columns={
    'Pct': 'Goal Four PCT'})
claim_four = claim_four.drop('Score', axis=1)
claim_four

,School,Student ID,Student Name,Grade,LangFlu,SPECIALED Value,Subject,Goal4Name,Goal4RitScore,Goal4Adjective,Goal Four PCT
0,6,1096561,"Mendez Juarez, Ximena",K,L,No,Language Arts,Vocabulary Use and Functions,102,Low,1
1,4,1096990,"Enriquez Lopez, Clarissa",K,L,No,Language Arts,Vocabulary Use and Functions,103,Low,1
2,4,1096444,"Rodriguez Nevarez JR, Carlos",K,E,Yes,Language Arts,Vocabulary Use and Functions,109,Low,1
3,4,1096955,"Barajas, Saul",K,L,Yes,Language Arts,Vocabulary Use and Functions,110,Low,1
4,6,1097045,"Carmen Lopez, Alan",K,L,No,Language Arts,Vocabulary Use and Functions,110,Low,1
...,...,...,...,...,...,...,...,...,...,...,...
294,6,1096295,"Rodriguez Almanza, Jessica",1,I,No,Language Arts,Vocabulary Use and Functions,183,High,95
295,4,1096497,"Medina, Katherine",1,E,No,Language Arts,Vocabulary Use and Functions,184,High,95
296,4,1096689,"Fernandez, Liam",1,E,Yes,Language Arts,Vocabulary Use and Functions,190,High,95
297,4,1096524,"Grewal, Armaan",1,E,No,Language Arts,Vocabulary Use and Functions,191,High,95
298,4,1096479,"Bejarano, Cassiopeia",1,E,No,Language Arts,Vocabulary Use and Functions,205,High,95

In [56]:
ela = pd.merge(claim_one, claim_two, how='outer', on=['School', 'Student ID', 'Student Name', 'Grade', 'LangFlu', 'SPECIALED Value', 'Subject'])
ela

,School,Student ID,Student Name,Grade,LangFlu,SPECIALED Value,Subject,Goal1Name,Goal1RitScore,Goal1Adjective,Goal One PCT,Goal2Name,Goal2RitScore,Goal2Adjective,Goal Two PCT
0,1,1092314,"Garcia, Isaias",8,L,Yes,Language Arts,Literary Text,212,Avg,35.0,Informational Text,200,Low,5.0
1,1,1092319,"Nunez Rodriguez, Stephanie",8,R,No,Language Arts,Literary Text,226,HiAvg,90.0,Informational Text,229,HiAvg,95.0
2,1,1092320,"Ragudo, Devin Maddox",8,E,No,Language Arts,Literary Text,228,HiAvg,95.0,Informational Text,238,High,95.0
3,1,1092327,"De Hoyos, Valentina",8,R,No,Language Arts,Literary Text,221,HiAvg,75.0,Informational Text,224,HiAvg,85.0
4,1,1092329,"Bragg, Haley",8,E,No,Language Arts,Literary Text,242,High,95.0,Informational Text,241,High,95.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2054,8,1096945,"Martinez Maravilla, Juliana",8,R,No,Language Arts,Literary Text,219,Avg,70.0,Informational Text,225,HiAvg,90.0
2055,8,1096967,"Ruiz, Gustavo",7,E,No,Language Arts,Literary Text,197,Low,5.0,Informational Text,186,Low,5.0
2056,8,1096988,"Carranza Mendoza, Katie",8,L,No,Language Arts,Literary Text,215,Avg,50.0,Informational Text,214,Avg,45.0
2057,8,1097021,"Barrera, Brianna",10,L,No,Language Arts,Literary Text,212,LoAvg,30.0,Informational Text,207,LoAvg,15.0
2058,999,1095414,"Rosales, Estela",5,L,No,Language Arts,Literary Text,192,LoAvg,10.0,Informational Text,186,Low,5.0

In [57]:
ela = pd.merge(ela, claim_three, how='outer', on=['School', 'Student ID', 'Student Name', 'Grade', 'LangFlu', 'SPECIALED Value', 'Subject'])
ela

,School,Student ID,Student Name,Grade,LangFlu,SPECIALED Value,Subject,Goal1Name,Goal1RitScore,Goal1Adjective,Goal One PCT,Goal2Name,Goal2RitScore,Goal2Adjective,Goal Two PCT,Goal3Name,Goal3RitScore,Goal3Adjective,Goal Three PCT
0,1,1092314,"Garcia, Isaias",8,L,Yes,Language Arts,Literary Text,212,Avg,35.0,Informational Text,200,Low,5.0,Vocabulary,192,Low,5.0
1,1,1092319,"Nunez Rodriguez, Stephanie",8,R,No,Language Arts,Literary Text,226,HiAvg,90.0,Informational Text,229,HiAvg,95.0,Vocabulary,230,HiAvg,95.0
2,1,1092320,"Ragudo, Devin Maddox",8,E,No,Language Arts,Literary Text,228,HiAvg,95.0,Informational Text,238,High,95.0,Vocabulary,233,High,95.0
3,1,1092327,"De Hoyos, Valentina",8,R,No,Language Arts,Literary Text,221,HiAvg,75.0,Informational Text,224,HiAvg,85.0,Vocabulary,229,HiAvg,95.0
4,1,1092329,"Bragg, Haley",8,E,No,Language Arts,Literary Text,242,High,95.0,Informational Text,241,High,95.0,Vocabulary,247,High,95.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2054,8,1096945,"Martinez Maravilla, Juliana",8,R,No,Language Arts,Literary Text,219,Avg,70.0,Informational Text,225,HiAvg,90.0,Vocabulary,207,LoAvg,15.0
2055,8,1096967,"Ruiz, Gustavo",7,E,No,Language Arts,Literary Text,197,Low,5.0,Informational Text,186,Low,5.0,Vocabulary,204,LoAvg,15.0
2056,8,1096988,"Carranza Mendoza, Katie",8,L,No,Language Arts,Literary Text,215,Avg,50.0,Informational Text,214,Avg,45.0,Vocabulary,204,LoAvg,10.0
2057,8,1097021,"Barrera, Brianna",10,L,No,Language Arts,Literary Text,212,LoAvg,30.0,Informational Text,207,LoAvg,15.0,Vocabulary,204,LoAvg,10.0
2058,999,1095414,"Rosales, Estela",5,L,No,Language Arts,Literary Text,192,LoAvg,10.0,Informational Text,186,Low,5.0,Vocabulary,186,Low,5.0

In [58]:
ela = pd.merge(ela, claim_four, how='outer', on=['School', 'Student ID', 'Student Name', 'Grade', 'LangFlu', 'SPECIALED Value', 'Subject'])
ela

,School,Student ID,Student Name,Grade,LangFlu,SPECIALED Value,Subject,Goal1Name,Goal1RitScore,Goal1Adjective,...,Goal2Adjective,Goal Two PCT,Goal3Name,Goal3RitScore,Goal3Adjective,Goal Three PCT,Goal4Name,Goal4RitScore,Goal4Adjective,Goal Four PCT
0,1,1092314,"Garcia, Isaias",8,L,Yes,Language Arts,Literary Text,212,Avg,...,Low,5.0,Vocabulary,192,Low,5.0,NaN,<NA>,NaN,NaN
1,1,1092319,"Nunez Rodriguez, Stephanie",8,R,No,Language Arts,Literary Text,226,HiAvg,...,HiAvg,95.0,Vocabulary,230,HiAvg,95.0,NaN,<NA>,NaN,NaN
2,1,1092320,"Ragudo, Devin Maddox",8,E,No,Language Arts,Literary Text,228,HiAvg,...,High,95.0,Vocabulary,233,High,95.0,NaN,<NA>,NaN,NaN
3,1,1092327,"De Hoyos, Valentina",8,R,No,Language Arts,Literary Text,221,HiAvg,...,HiAvg,85.0,Vocabulary,229,HiAvg,95.0,NaN,<NA>,NaN,NaN
4,1,1092329,"Bragg, Haley",8,E,No,Language Arts,Literary Text,242,High,...,High,95.0,Vocabulary,247,High,95.0,NaN,<NA>,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2054,8,1096945,"Martinez Maravilla, Juliana",8,R,No,Language Arts,Literary Text,219,Avg,...,HiAvg,90.0,Vocabulary,207,LoAvg,15.0,NaN,<NA>,NaN,NaN
2055,8,1096967,"Ruiz, Gustavo",7,E,No,Language Arts,Literary Text,197,Low,...,Low,5.0,Vocabulary,204,LoAvg,15.0,NaN,<NA>,NaN,NaN
2056,8,1096988,"Carranza Mendoza, Katie",8,L,No,Language Arts,Literary Text,215,Avg,...,Avg,45.0,Vocabulary,204,LoAvg,10.0,NaN,<NA>,NaN,NaN
2057,8,1097021,"Barrera, Brianna",10,L,No,Language Arts,Literary Text,212,LoAvg,...,LoAvg,15.0,Vocabulary,204,LoAvg,10.0,NaN,<NA>,NaN,NaN
2058,999,1095414,"Rosales, Estela",5,L,No,Language Arts,Literary Text,192,LoAvg,...,Low,5.0,Vocabulary,186,Low,5.0,NaN,<NA>,NaN,NaN

### Finishing Up

To generate one final dataframe, the math dataframe and the ela dataframe are concatenated. Then a CVS file is generated that will allow for download.

In [59]:
final = pd.concat([math, ela])
final

,School,Student ID,Student Name,Grade,LangFlu,SPECIALED Value,Subject,Goal1Name,Goal1RitScore,Goal1Adjective,...,Goal2Adjective,Goal Two PCT,Goal3Name,Goal3RitScore,Goal3Adjective,Goal Three PCT,Goal4Name,Goal4RitScore,Goal4Adjective,Goal Four PCT
0,1,1092314,"Garcia, Isaias",8,L,Yes,Mathematics,Operations and Algebraic Thinking,189,Low,...,Low,5.0,Geometry,201,Low,10.0,Statistics and Probability,196,Low,10.0
1,1,1092319,"Nunez Rodriguez, Stephanie",8,R,No,Mathematics,Operations and Algebraic Thinking,241,High,...,High,80.0,Geometry,230,HiAvg,65.0,Statistics and Probability,212,LoAvg,30.0
2,1,1092320,"Ragudo, Devin Maddox",8,E,No,Mathematics,Operations and Algebraic Thinking,241,High,...,High,95.0,Geometry,243,High,85.0,Statistics and Probability,250,High,95.0
3,1,1092327,"De Hoyos, Valentina",8,R,No,Mathematics,Operations and Algebraic Thinking,239,High,...,High,95.0,Geometry,239,High,80.0,Statistics and Probability,239,High,80.0
4,1,1092329,"Bragg, Haley",8,E,No,Mathematics,Operations and Algebraic Thinking,244,High,...,High,95.0,Geometry,241,High,85.0,Statistics and Probability,240,High,85.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2054,8,1096945,"Martinez Maravilla, Juliana",8,R,No,Language Arts,Literary Text,219,Avg,...,HiAvg,90.0,Vocabulary,207,LoAvg,15.0,NaN,<NA>,NaN,NaN
2055,8,1096967,"Ruiz, Gustavo",7,E,No,Language Arts,Literary Text,197,Low,...,Low,5.0,Vocabulary,204,LoAvg,15.0,NaN,<NA>,NaN,NaN
2056,8,1096988,"Carranza Mendoza, Katie",8,L,No,Language Arts,Literary Text,215,Avg,...,Avg,45.0,Vocabulary,204,LoAvg,10.0,NaN,<NA>,NaN,NaN
2057,8,1097021,"Barrera, Brianna",10,L,No,Language Arts,Literary Text,212,LoAvg,...,LoAvg,15.0,Vocabulary,204,LoAvg,10.0,NaN,<NA>,NaN,NaN
2058,999,1095414,"Rosales, Estela",5,L,No,Language Arts,Literary Text,192,LoAvg,...,Low,5.0,Vocabulary,186,Low,5.0,NaN,<NA>,NaN,NaN

In [60]:
import base64
from IPython.display import HTML

def create_download_link( df, title = "NWEA Categories", filename = "NWEA Categories"):
    csv = df.to_csv(index=False)
    b64 = base64.b64encode(csv.encode())
    payload = b64.decode()
    html = '<a download="{filename}" href="data:text/csv;base64,{payload}" target="_blank">{title}</a>'
    html = html.format(payload=payload,title=title,filename=filename)
    return HTML(html)

create_download_link(final)